// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b133f95b-dc68-4dd9-87a8-410da4071413",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_N2ltlsQpB",
    "aws_user_pools_web_client_id": "7v1gmti16qfvug5g1qn5l86r4e",
    "aws_appsync_graphqlEndpoint": "https://vkyu4k524bhr5dv4c2xlcfnolm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-q3ndsvolszhgximnsyysn222ui",
    "aws_content_delivery_bucket": "chatboard-20190120205109-hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://chatboard-20190120205109-hostingbucket.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
